create table customer
(
    id    int generated by default as identity primary key,
    name  varchar(255),
    phone varchar(255),
    email varchar(255)
);

create table orders
(
    id          int generated by default as identity primary key,
    customer_id int references customer (id),
    status      varchar(255),
    created_at  timestamp
);

create table product
(
    id        int generated by default as identity primary key,
    name      varchar(255),
    price     numeric(38, 2),
    stock_qty int
);


create table order_item
(
    id             int generated by default as identity primary key,
    price_at_order numeric(38, 2),
    quantity       int,
    order_id       int references orders (id),
    product_id     int references product (id)
);